apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    spec:
      nodeSelector:
        env: batch
      containers:
      - name: training-kanelectra-autoencoder
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python", "scripts/pretraining/train.py"]
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /data
        - name: outputs
          mountPath: /outputs
      volumes:
      - name: data
        emptyDir: {}
      - name: outputs
        persistentVolumeClaim:
          claimName: checkpoints-klassikcat
      restartPolicy: Never 