image:
  repository: electrakan
  tag: latest
  pullPolicy: IfNotPresent

job:
  name: electra-training
  backoffLimit: 4
  ttlSecondsAfterFinished: 100

resources:
  limits:
    cpu: "8"
    memory: "16Gi"
    nvidia.com/gpu: "4"
  requests:
    cpu: "8"
    memory: "8Gi"
    nvidia.com/gpu: "4"

config:
  tokenizer_name: "klue/bert-base"
  datasets:
    train:
      path: "/data/train.csv"
      max_length: 512
      text_row: "text"
    val:
      path: "/data/val.csv"
      max_length: 512
      text_row: "text"
    test:
      path: "/data/test.csv"
      max_length: 512
      text_row: "text"
  datamodule:
    batch_size: 32
    num_workers: 4
    pin_memory: true
  trainer:
    max_epochs: 10
    accelerator: "gpu"
    devices: 1
    precision: "16-mixed"
    callbacks:
      - name: ModelCheckpoint
        params:
          dirpath: "/outputs/checkpoints"
          filename: "electra-{epoch:02d}-{val_loss:.2f}"
          save_top_k: 3
          monitor: "val_loss"
          mode: "min" 